### PR TITLE
use XSeries as a dependency

### PR DESCRIPTION
**Pull request by HSGamer**

### CODE REVIEW

**Comment by montlikadani** [comment]
This needs a repackage (re-import) for all of Plugily's projects :(
Imma too lazy to do that

**Comment by HSGamer** [comment]
> This needs a repackage (re-import) for all of Plugily's projects :(
> Imma too lazy to do that

It's already relocated. You just need to update the Commons-Box dependency.

**Comment by HSGamer** [comment]
In addition, I've relocated the package to the same package as the current XSeries. You just need to build it and the output jar will be the same as your old dependency.

**Comment by montlikadani** [comment]
> You just need to update the Commons-Box dependency.

This @Tigerpanzer02's job

**Pull request merged**
